---
- hosts: all
  sudo: true

  roles:
    - common
    - nginx

  post_tasks:
    - name: create the prez site
      copy: src=files/nginx-site.j2 dest=/etc/nginx/sites-available/prez
      tags: nginx

    - name: enable the prez site
      file: src=/etc/nginx/sites-available/prez dest=/etc/nginx/sites-enabled/prez state=link
      tags: nginx

    - name: disabled the default nginx-site
      file: path=/etc/nginx-sites-enables/dummy state=absent
      tags: nginx

    - name: reload the nginx conf
      service: name=nginx state=reloaded
      tags: nginx

    - name: install basic packages
      apt: pkg={{ item }} state=present
      with_items:
        - python-dev
        - python-pip
       
    - name: install moar basic packages
      pip: name={{ item }} state=present
      with_items:
        - ipython
        - pyjade

